Lesson5 acceptance testing three us
vikkanaev/ViksTnetica17 pull request #4
Opened 2017-10-17 05:13 UTC by vikkanaev

Закончены все US из урока5
Истории реализовывались последовательно, строго в соответствии со списком.
1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2017-10-17 09:30 UTC, vkurennov requested changes

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def index
Нам не нужны экшены index, new и show, потому что список ответов должен находится на странице вопросов, там же и форма создания нового ответа, а страницы отельного ответа вообще не должно быть.

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def edit
Про edit у нас в заданиях пока ничего не было, поэтому и добавлять его не нужно

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show'
Тут все верно, и этот еще раз доказывает, что new и show для ответов не нужны

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user_id == current_user.id && @answer.destroy
Сравнение по user_id верное, но оно нам много где потребуется, поэтому стоит его вынести в метод `User#author_of?` и вызывать этот метод

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
редиректы одинаковые, почему они тогда в условии?

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:title, :body)
у ответа не должно бытль title, зачем он?

2017-10-17 09:30 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user_id == current_user.id && @question.destroy
Замени на вызов `User#author_of?`

2017-10-17 09:30 UTC, vkurennov commented on app/models/answer.rb
>    validates :title, :body, presence: true
Зачем ответу title?

2017-10-17 09:30 UTC, vkurennov commented on app/views/answers/new.html.slim
> +p New answer view
Удали это  вид и экшн для него

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/index.html.slim
> +- for question in @questions
Используй each, забудь про цикл for, он не используется по факту. Его всегда можно заменить на each

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  h3 #{question.title}
Хорошо бы это сделать ссылкой на страницу вопроса.

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  br
А тут хорошо бы добавить ссылку на создание нового вопроса.

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/new.html.slim
> +  p All fields are required!
Слишком хитро. Надо выводить реальные ошибки валидации

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to 'Delete Question', question_path(@question), method: :delete
Зачем показывать ссылку всем? Показывай только автору вопроса

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = link_to 'Delete Answer', answer_path(answer), method: :delete
И тут показывай ссылку только автору ответа

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  p All fields are required in Answer!
Показывай реальные ошибки валидации

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = form_for [@question, Answer.new] do |f|
Сюда вторым параметром надо тоже передавать @answer, иначе, при ошибках валидации, юзер вынужден будет все вводить заново, отредактировать ответ и исправить ошибки будет нельзя

2017-10-17 09:30 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = f.label :title
Посмотри на оригинальный stackoverflow. Разве у него есть заголовок? Это просто неудобно. Мало того, что ты ответил на вопрос, так тебе еще надо как-то озаглавить свой ответ, что может быть затруднительно. Поэтому просто убери title у ответов

2017-10-17 09:30 UTC, vkurennov commented on config/routes.rb
> +  resources :answers, only: [:update, :destroy]
Прочитай про опцию shallow в роутах и используй ее, она как раз делает то, что нужно.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить наличие заголовка и тела вопроса на странице

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    visit new_question_path
Тут нужен полный сценарий, когда пользователь заходит на главную страницу и кликает по ссылке "Задать вопрос", иначе получается, что у тебя юзер ввел url. Из-за этого, ты в интерфейсе упустил некоторые детали и пользоваться приложением неудобно.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    visit new_question_path
Опять же нужно весь сценарий повторить, с захода на главную

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +feature 'View the list of questions', %q{
Каждая фича в отдельном файле должне быть

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    Question.create(title: 'Title1', body: 'Long long story1')
Используй let и фабрики. И лучше создать список из 5-8 вопросов (чтобы были уникальными, используй sequence в фабриках) и проверить их в цикле.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    expect(page).to have_content 'Long long story2'
Почему проверяешь только один ответ из списка.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    @question.answers.create(title: 'Answer1', body: 'MyAnswerText')
Нужно список ответов проверять, т.е. их должно быть несколько (5-8) и они должны быть разными.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +feature 'Delete question from the question page', %q{
Это опять же должна быть отдельный файл

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +# Автор может удалить свой вопрос, но не может удалить чужой вопрос
Ты описание фичи делай таким, чтобы не пришлось комментровать и писать перевод

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    expect(page).to have_content 'Your question successfully deleted'
Надо проверить, что вопроса больше нет на странице

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +    click_on 'Delete Question'
Лучше не показыауть ссылку и проверять то, что юзер ее не видит.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/1_question_spec.rb
> +  scenario 'User can not delete other users questions' do
Нужен аналогичный сценарий для незалогиненного юзера

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +    fill_in 'Body', with: question.body
Это опасно тем, что даже если ты будешь проверять наличие этого контента на странице, то тест всегда пройдет, потому что заголовок и тело **вопроса** уже есть. Поэтому для ответа надо вводить другие данные.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +    expect(page).to have_content 'Your answer successfully created.'
Нужно проверить наличие созданного ответа на странице

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +    visit question_path(question)
Гость может видеть страницу вопроса, он ответ создавать не может. Но зайти-то на страницу вопроса он должен, поэтому сценарий неверный.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +feature 'Delete answer from the question page', %q{
Вынеси в отдельный файл

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +    expect(page).to have_content 'Your answer successfully deleted'
Нужно проверить, что ответа больше нет на странице.

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +    click_on 'Delete Answer'
просто не показывай ссылку

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/2_answer_to_question_spec.rb
> +  scenario 'User can not delete other users answers' do
Нужен такой же сценарий для незалогиненного юзера

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/3_user_login_logout_registrate_spec.rb
> +  feature 'User logout', %q{
Вынеси в отдельный файл

2017-10-17 09:30 UTC, vkurennov commented on spec/acceptance/3_user_login_logout_registrate_spec.rb
> +    feature 'GuestUser registration', %q{
Вынеси в отдельный файл

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'POST #create' do
Отделяй пустыми строками блок начальных данных от describe. также методы, сценарии, тесты отделяются друго от друга пустой строкой - это сильно облегчает чтение. как абзацы в тексте. Пройдись по всему коду и везде это поправь.

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'saves the new answer in the database' do
Перед тестом нужна пустая строка

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'renders parent question' do
Перед тестом нужна пустая строка

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: invalid_params }.to_not change(question.answers, :count)
Тут в change должно быть просто Answer: важно проверить, что не был создан вообще никакой ответ, вне зависимотси от его связи с вопросом

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
В этом контексте нужно проверить связь ответа с залогиненным юзером.

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          expect { delete :destroy, params: { id: author_answer } }.to change(Answer, :count).by(0)
мы же не говорим "изменился на ноль", мы говорим "не изменился". Вот и используй `to_not change`

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: author_answer } }.to change(Answer, :count).by(0)
`to_not change`

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +#    log_in_user
Удаляй закомментирвоанный код, нечего хранить хлам.

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
Нужен тест на связь вопроса и залогиненного юзера

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0)
`to_not change`

2017-10-17 09:30 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0)
`to_not change`

2017-10-17 09:30 UTC, vkurennov commented on spec/factories/questions.rb
> +  factory :question2 do
Зачем тебе еще одна фабрика, которая создает точно такой же вопрос, что и первая фабрика? Ты же в тестах просто 2 раза можешь вызывать create и у тебя будет создано 2 вопроса, но используется одна фабрика.

2017-10-19 05:23 UTC, vikkanaev commented on app/views/questions/show.html.slim
> +  = form_for [@question, Answer.new] do |f|
Не уверен что понял

2017-10-19 08:57 UTC, vkurennov requested changes

2017-10-19 08:57 UTC, vkurennov commented on app/assets/javascripts/application.js
> +//= require jquery_ujs
ОСтавь либо это, либо rails-ujs, а то потом конфликты будут

2017-10-19 08:57 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    # А как, блин тут быть?
В чем именно проблема? Тут верный код.

2017-10-19 08:57 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(@answer.question_id)
Зачем тебе делать поиск вопроса по id, если ассоциация `@answer.question` и так даст тебе нужный объект? И опять же, не надо его сохранять в переменную, ты можешь просто в редиректе указать `redirect_to @answer.question`. Несмотря на то, что ответ ты удалил, в памяти он еще есть, вместе со всеми ассоциациями и ты можешь их использовать

2017-10-19 08:57 UTC, vkurennov commented on app/views/questions/index.html.slim
> +   = link_to question.title, question_path(question)
Можно вторым параметром просто `question` передавать, будет то же самое, только короче

2017-10-19 08:57 UTC, vkurennov commented on app/views/questions/show.html.slim
> +     = link_to 'Delete Answer', answer_path(answer), method: :delete if current_user.author_of?(answer)
Лучше вметсто 2-х if просто объеденить условия в один if

2017-10-19 08:57 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = form_for [@question, Answer.new] do |f|
Вот смотри: у тебя при входе на страницу тут в форме создается новый ответ Answer.new. И при попытке его создания, если были ошибки валидации и снова отрендерилась эта страница, у тебя все содержимое находится в объекте @answer. Чтобы ты не чистую форму и ошибки показал юзеру, а дал ему возможность их исправить, нужно вторым параметром указыать @answer в форме (`[@question, @answer]`).

А чтобы форма работала и для первого входа на страницу, нужно в `QuestionsController#show` добавить строчку:

`@answer = Answer.new`

Тогда в форме у тебя всегда будет переменная @answer, но что именно в ней, будет зависеть от того, какой контроллер и экшн отрендерил эту форму.

2017-10-19 08:57 UTC, vkurennov commented on spec/acceptance/questions/1_create_question_spec.rb
> +  scenario 'Question not created without Body' do
Не нужно все ошибки валидации тестировать, мы это делаем в тестах моделей, тут достаточно проверить, что в принципе ошибки валидации выводятся на страницу.

2017-10-19 08:57 UTC, vkurennov commented on spec/acceptance/questions/2_view_questions_list_spec.rb
> +  # не нашел пока как обернуть нестед вопрос в create_list
Очень просто:

`let(:answers) { create_list(:answer, 5, question: one_question, user: user_author) }`

2017-10-19 08:57 UTC, vkurennov commented on spec/acceptance/questions/2_view_questions_list_spec.rb
> +    @answers = Array.new
Пустые массивы в руби принято объявлять как `[]`

2017-10-19 08:57 UTC, vkurennov commented on spec/acceptance/questions/3_delete_question_spec.rb
> +  scenario 'User can not delete other users questions' do
Такой же тест нужен для незалогиненного пользователя

2017-10-19 08:57 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it { expect(user_author).to respond_to(:author_of?) }
Это лишний тест, ты же дальше и так вызываешь этот метод, значит, проверяешь и его наличие, потому что если его не будет, тест упадет.

2017-10-20 08:45 UTC, vkurennov approved these changes

2017-10-20 08:45 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it { expect(user_author.author_of?(question)).to be(true) }
У тебя же было правильно. гораздо красивее писать так:

`expect(user).to be_author_of?(question)`

2017-10-20 09:50 UTC, merged