Lesson7 ajax part2
vikkanaev/ViksTnetica17 pull request #6
Opened 2017-11-06 19:47 UTC by vikkanaev

Выполнил задания урока Ajax part2

2017-11-10 10:37 UTC, vkurennov requested changes

2017-11-10 10:37 UTC, vkurennov commented on app/assets/javascripts/questions.coffee
> +    $.ajax({
Мы говорили о том, что это надо переделать на remote-ссылку в видах

2017-11-10 10:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.save!
Зачем ты сохраняешь вопрос? Он же не изменился, ассоциаиции имзенения автоматически учитывают

2017-11-10 10:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      # Как тут лучше сделать?
Дело не в проверке, потому что вызов destroy не означает рендер вида, вид рендерится только после того, как экшн закончил свою работу. Дело в том, что установка flash видна только в следующем запросе, т.е. при редиректе, а тут его нет и он не нужен. Чтобы flash был виден в текщуем запросе, нужно устанавливать его так: `flash.now[:notice] =' ...'`. В видах испольузешь как обычно.

2017-11-10 10:37 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def set_best_answer_ever
Этот экшн должен быть в AnswersController

2017-11-10 10:37 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :best_answer_id)
best_answer_id здесь больше не нужен

2017-11-10 10:37 UTC, vkurennov commented on app/models/question.rb
> +#  def only_one_best_answer
Я в отчете твоем написал, что нужно сделать, чтобы проверка работала

2017-11-10 10:37 UTC, vkurennov commented on app/views/answers/create.js.erb
> +    $('.best-answer-link').on('click', function(ba) {
Это будет не нужно, если сделать remote-ссылку

2017-11-10 10:37 UTC, vkurennov commented on app/views/questions/_answers.html.slim
> +          b= link_to 'Chois as Best', "/questions/#{@question.id}/set_best_answer_ever/#{answer.id}", method: :patch, remote: true
Для пути  в сссылке используй url-хепер. И заставь ссылку работать. убрав обработчики из скриптов для нее.

2017-11-10 10:37 UTC, vkurennov commented on app/views/questions/set_best_answer_ever.js.erb
> +  $.ajax({
Опять лишнее

2017-11-10 10:37 UTC, vkurennov commented on config/routes.rb
> +  patch  '/questions/:id/set_best_answer_ever/:best_answer_id', to: 'questions#set_best_answer_ever'
Это должен быть кастомный экшн в ресурсе answers

2017-11-11 10:12 UTC, vkurennov approved these changes

2017-11-11 10:12 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :load_question, only: [:show, :edit, :destroy, :update, :set_best_answer_ever]
У тебя больше нет здесь экшена set_best_answer_ever, удали его из списка.

2017-11-11 10:12 UTC, vkurennov commented on spec/acceptance/answer/4_best_answer_choice_spec.rb
> +      expect(page).to have_content "Set answer #{best_answer.id} as best answer ever!"
Надо проверить, что овтет стал первым в списке.

2017-11-11 10:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  describe 'public model methods' do
Обычно делается describe на каждый отдельный метод. И нет смысла указывать, что это именно публичные методы, ведь мы только их и тестируем.

2017-11-11 10:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +        expect(question.answers.where(best: false).ids[0]).to eq best_answer.id
Зачем тут по id сравнивать? Лучше уж объект сравнить

2017-11-11 10:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      question.reload
Зачем перехагружать вопрос? Надо перезагрузить его ответы: `question.answers.reload`

2017-11-11 10:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +        expect(question.answers.where(best: false).ids[0]).to eq best_answer.id
Красивее было бы написать так:
`expect(best_answer).to_not be_best`

2017-11-12 16:02 UTC, vikkanaev commented on spec/acceptance/answer/4_best_answer_choice_spec.rb
> +      expect(page).to have_content "Set answer #{best_answer.id} as best answer ever!"
Сделанно!

2017-11-12 16:26 UTC, merged